CLASS zbp_co002_cev_kalan_bakiye DEFINITION PUBLIC ABSTRACT FINAL FOR BEHAVIOR OF zco002_cev_kalan_bakiye.

*PUBLIC SECTION.
  CLASS-DATA: mv_test TYPE int8.
ENDCLASS.



CLASS ZBP_CO002_CEV_KALAN_BAKIYE IMPLEMENTATION.
ENDCLASS.
